### ISSUE TITLE
Does not run on Windows Server 2008

### ISSUE THREAD

**Issue by temp-malware** [NYAN-x-CAT/AsyncRAT-C-Sharp#121]
sub.exe does not work on Windows Server 2008 operating system

**Comment by NYAN-x-CAT-is-My-Brother** [comment]
Did you installed the latest version of dotnet framework ? Read the description   below " AsyncRAT requires the .Net Framework v4 (client) and v4.6+ (server) to run."

**Comment by temp-malware** [comment]
yes I did it by paying attention to the instructions.
Operating systems I've tested: Windows 7, Windows 8, Windows 8.1, Windows 10,

But I cannot communicate with the Server 2008 operating system.

**Comment by NYAN-x-CAT-is-My-Brother** [comment]
Did you test the same stub on Windows 7, Windows 8, Windows 8.1, Windows 10, and Windows Server 2008 or different stub ? if the same stub works on ( Windows 7, Windows 8, Windows 8.1, Windows 10) and not works on windows server 2008 then may be it's a problem.otherwise,if you use different stub then i sense your settings or server problem

**Comment by temp-malware** [comment]
I do not understand what the problem is.
AsyncRAT-Sharp runs smoothly.

But client.exe did not work on server 2008.

just wanted to inform :)

**Comment by NYAN-x-CAT** [comment]
Double-check everything.
Remember to disable some policies. *assuming you know how to use WIN servers*
It will be hard to detect the problem because this is a user fault, not a program fault.
https://prnt.sc/pj5t0p
